[package]
name = "bugger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.3", features = ["derive"] }
chrono = { version = "0.4.30", features = ["clock"] }
csv = "1.2.2"
prettytable-rs = "0.10.0"
